# .readthedocs.yaml
# Almost verbatim from:
# https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    pre_create_environment:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
    create_environment:
        - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
        - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs

mkdocs:
  configuration: mkdocs.yml
