# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Also https://blog.readthedocs.com/migrate-configuration-v2/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
    uv: "latest"

# Build documentation in the docs/ directory with MkDocs
mkdocs:
  configuration: mkdocs.yml
