%%{init: { 'gitGraph': {'mainBranchOrder': 10}} }%%

gitGraph
    commit
    commit

    branch dev order:10
    commit

    branch feat-1-make-hay order:21
    commit
    commit

    checkout dev
    merge feat-1-make-hay

    checkout dev
    commit

    checkout dev
    branch feat-2-eat-dirt order:22
    commit
    checkout dev
    merge feat-2-eat-dirt
    commit

    checkout main
    merge dev

    branch release-1.1
    commit tag:"1.1.1"

    checkout release-1.1
    commit tag:"1.1.1"
    branch fix-1
    commit
    checkout release-1.1
    merge fix-1 tag:"1.1.2"

    checkout main
    merge fix-1

    checkout dev
    merge main

    checkout dev
    commit
    branch feat-3-get-lost order:23
    commit
    checkout dev
    merge feat-3-get-lost
    commit

    checkout main
    merge dev

    branch release-1.2
    commit tag:"1.2.1"

    checkout dev
    commit

    checkout release-1.2
    commit tag:"1.2.2"
